import type { Metadata } from "next";
import "../globals.css"; // Import global styles
import { ClerkProvider } from "@clerk/nextjs"; // Clerk for authentication
import Header from "./../../components/Header";
import Footer from "./../../components/Footer";

// Metadata for the page
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode; // Specify children prop type
}>) {
  return (
    <ClerkProvider dynamic>
      <html lang="en">
        <body className={`antialiased`}>
            <Header />
          <main >
            {children}
            
          </main>
            <Footer/>
        </body>
      </html>
    </ClerkProvider>
  );
}
